# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20171201_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer3',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
