# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20171201_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='theme',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
