# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_question_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
