# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_question_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='section',
        ),
    ]
