# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_remove_question_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer4',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer5',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
