# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20171207_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
