# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='theme',
            field=models.IntegerField(default=0),
        ),
    ]
