# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_auto_20180223_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='theme',
            field=models.IntegerField(),
        ),
    ]
