# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ass',
            field=models.CharField(default='q', max_length=10),
            preserve_default=False,
        ),
    ]
