# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_question_ass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='ass',
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.IntegerField(),
        ),
    ]
