# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-29 11:07
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_theorytheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theorytheme',
            name='themes',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=None), size=None), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theorytheme',
            name='theme_name',
            field=models.TextField(default=None),
        ),
    ]
