# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-05 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_auto_20180730_1932'),
        ('exam', '0021_auto_20180729_1107'),
    ]

    operations = [
    ]
