#!/bin/bash

NAME="znatok"
DIR=/root/znatok
USER=root
GROUP=root
WORKERS=3
BIND=unix:/root/znatok/run/gunicorn.sock
DJANGO_SETTINGS_MODULE=znatokPDD.settings
DJANGO_WSGI_MODULE=znatokPDD.wsgi
LOG_LEVEL=error

cd $DIR
source /root/znatok/venv/bin/activate

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DIR:$PYTHONPATH

exec /root/znatok/venv/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $WORKERS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-
