# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-10 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180208_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='state',
        ),
        migrations.AddField(
            model_name='result',
            name='user_answer',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
