# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-20 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180304_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-points']},
        ),
        migrations.AddField(
            model_name='profile',
            name='last_mini_game',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
