# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-22 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180320_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_mini_game',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
