# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-24 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180322_0040'),
        ('accounts', '0007_auto_20180324_1617'),
    ]

    operations = [
    ]
