# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-27 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20180324_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_password_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_avatar',
            field=models.ImageField(blank=True, default='profile_avatar/default.png', upload_to='profile_avatar/'),
        ),
    ]
