# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-27 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180327_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_password_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
