# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-01 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180327_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='online_game_count_of_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='online_game_total_games',
            field=models.IntegerField(default=0),
        ),
    ]
