# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-01 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180401_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_img', models.ImageField(blank=True, upload_to='rank_img/')),
                ('rank_title', models.CharField(max_length=200)),
                ('rank_description', models.CharField(max_length=200)),
                ('rank_point', models.IntegerField(default=0)),
                ('rank_reward_point', models.IntegerField(default=0)),
            ],
        ),
    ]
