# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-01 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20180701_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rank_progress',
            field=models.IntegerField(default=0),
        ),
    ]
