# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-01 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_profile_rank_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='rank_point',
        ),
    ]
