# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-01 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_rank_rank_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='rank_img_disable',
            field=models.ImageField(blank=True, upload_to='rank_img/'),
        ),
    ]
